# Generated by Django 3.2.24 on 2024-02-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('introduction', models.TextField(max_length=700)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
